spring.application.name=seguros
server.port=9091
# Cambia la URL para acceder al HTML de Swagger
springdoc.swagger-ui.path=/swagger-ui.html
# Cambia la URL donde se genera el JSON con la especificación OpenAPI v3
springdoc.api-docs.path=/api-docs